### ISSUE TITLE
İlk açılışta hata

### ISSUE THREAD

**Issue by berkayoruc** [tekangun/fh-humanity#1]
Uygulama ilk kez açılıyorsa ve konum bilgisi yoksa resimdeki hata alınıyor

![IMG_20210207_220532_657.jpg](https://user-images.githubusercontent.com/22800134/107156650-a20e8600-6990-11eb-988d-54cfa258f983.jpg)

**Comment by tekangun** [comment]
Öncelikle teşekkürler. Test aşamasındayken çalışması gerektiğinden daha erken çalışan bir fonksiyon kullanmıştım onu silmeyi unutmuşum. Şu anda düzelmiş versiyonu mevcut.

**Comment by berkayoruc** [comment]
Tam olarak demek istediğim düzelttiğin yer değil

**Comment by berkayoruc** [comment]
f062fccc1d38084a4a0cd364f046fc770cdc77d1 commiti ile bahsedilen fonksiyon entegre edildi
