### ISSUE TITLE
Anasayfa text overflow

### ISSUE THREAD

**Issue by berkayoruc** [tekangun/fh-humanity#2]
Anasayfada güncelleme zamanı overflow oluyor düzeltilmesi lazım

![IMG_20210207_220536_970.jpg](https://user-images.githubusercontent.com/22800134/107156687-da15c900-6990-11eb-8fdb-0c5803e80dca.jpg)

![Screenshot_20210207-214630.jpg](https://user-images.githubusercontent.com/22800134/107156690-deda7d00-6990-11eb-9ec6-316872f37d88.jpg)

**Comment by tekangun** [comment]
Bildiri için teşekkürler. Zaman bildirgecinin gereksiz uzun olduğunu farkettim sayende bu sebeple 'Son güncellenme Tarihi' yerine 'Güncellenme' yazısını kullanmaya karar verdim. Aynı zamanda tarih içerisindeki gereksiz 2 adet 0'ı sildim.
